name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Move Dir
      run: cd bellmetal;
           ls -l
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
